version: '3'

services:
  web:
    build: .
    container_name: catalog_app
    ports:
      - 8080:8080
    volumes: 
      - ../:/work
    depends_on: 
      - db
    tty: true

  db:
    image: mysql:8.0.19
    container_name: catalog_db
    environment: 
      - MYSQL_ROOT_PASSWORD=password
