version: '3'

services:
  web:
    build: .
    container_name: catalog_app
    ports:
      - 8080:8080
    volumes: 
      - ../:/work
    depends_on: 
      - db
    tty: true
    environment:
      - TZ=Asia/Tokyo

  db:
    image: mysql:8.0.19
    container_name: catalog_db
    ports:
      - 3308:3306
    environment: 
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=catalog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
